// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALhU4lS4uwzoGhYX-nRDybZGtNeQ0cM1A',
    appId: '1:42782022592:web:0a4f68dc651e57212fc625',
    messagingSenderId: '42782022592',
    projectId: 'fruithub-973f6',
    authDomain: 'fruithub-973f6.firebaseapp.com',
    storageBucket: 'fruithub-973f6.appspot.com',
    measurementId: 'G-84KX7QWETP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_oaLnG8d2cMm_PVOkMEZCznXA1uGjU9E',
    appId: '1:42782022592:android:1a97900b174b0bce2fc625',
    messagingSenderId: '42782022592',
    projectId: 'fruithub-973f6',
    storageBucket: 'fruithub-973f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChGtdNgF-cMFj-Oz-OwLsajaKuCdWjpKU',
    appId: '1:42782022592:ios:e9b86a3e54acbfd12fc625',
    messagingSenderId: '42782022592',
    projectId: 'fruithub-973f6',
    storageBucket: 'fruithub-973f6.appspot.com',
    iosBundleId: 'com.example.fruits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChGtdNgF-cMFj-Oz-OwLsajaKuCdWjpKU',
    appId: '1:42782022592:ios:e9b86a3e54acbfd12fc625',
    messagingSenderId: '42782022592',
    projectId: 'fruithub-973f6',
    storageBucket: 'fruithub-973f6.appspot.com',
    iosBundleId: 'com.example.fruits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALhU4lS4uwzoGhYX-nRDybZGtNeQ0cM1A',
    appId: '1:42782022592:web:a70787ad9c2549262fc625',
    messagingSenderId: '42782022592',
    projectId: 'fruithub-973f6',
    authDomain: 'fruithub-973f6.firebaseapp.com',
    storageBucket: 'fruithub-973f6.appspot.com',
    measurementId: 'G-Z15M3BFL0D',
  );
}
